//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManufacturingCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Contact
    {
        public int Id { get; set; }
        public int customer_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string work_phone { get; set; }
        public string mobile_phone { get; set; }
        public string fax { get; set; }
        public string contact_email { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
