//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManufacturingCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery_Lineitem
    {
        public int Id { get; set; }
        public int product_inventory_id { get; set; }
        public int lineitem_unit_quantity { get; set; }
        public int delivery_schedule_id { get; set; }
    
        public virtual Delivery_Schedule Delivery_Schedule { get; set; }
        public virtual Product_Inventory Product_Inventory { get; set; }
    }
}
