//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManufacturingCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.Equipment_Maintenance = new HashSet<Equipment_Maintenance>();
        }
    
        public int Id { get; set; }
        public string equipment_name { get; set; }
        public string equipment_short_description { get; set; }
        public string equipment_long_description { get; set; }
        public string equipment_note { get; set; }
        public decimal equipment_cost { get; set; }
        public Nullable<int> product_id { get; set; }
        public bool in_maintenance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment_Maintenance> Equipment_Maintenance { get; set; }
        public virtual Product Product { get; set; }
    }
}
