//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManufacturingCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Lineitem : Lineitem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice_Lineitem()
        {
            this.Delivery_Lineitem = new HashSet<Delivery_Lineitem>();
        }
    
        public int Id { get; set; }
        public int invoice_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delivery_Lineitem> Delivery_Lineitem { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual Product_Inventory Product_Inventory { get; set; }
    }
}
