//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManufacturingCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_Stock
    {
        public int Id { get; set; }
        public int material_id { get; set; }
        public string material_unit_measure { get; set; }
        public int material_unit_quantity { get; set; }
        public decimal material_unit_cost { get; set; }
    
        public virtual Material Material { get; set; }
    }
}
