//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManufacturingCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paycheck
    {
        public int Id { get; set; }
        public int payroll_id { get; set; }
        public string payment_type { get; set; }
        public string check_number { get; set; }
        public string direct_deposit_number { get; set; }
        public decimal payment_amount { get; set; }
    
        public virtual Payroll Payroll { get; set; }
    }
}
