//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManufacturingCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterUserRoleModel
    {
        public string UserID { get; set; }
        public string RoleName { get; set; }
        public string UserObject_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
